
model_name: test_case_1
model_description: dummy case study for testing the model
model_data_folder_path: D:\Politecnico di Milano\Documentale DENG - PRIN-MIMO\Models\pyESM_docs\case_studies

database_settings:
    generate_blank_sets: true
    sets_file_name: sets.xlsx
    generate_database_sql: false
    database_sql_name: database.db

data_dir_settings:
    data_dir_name: input_data
    # hierarchy: {directories: None, files: scenarios, sheets: variables}
    hierarchy: {directories: scenarios, files: variables, sheets: None}
    # hierarchy: {directories: None, files: variables, sheets: scenarios}

problem_settings:
    execution_mode: simulation