
general:
    model_name: test_case_1
    model_description: dummy case study for testing the model
    model_data_dir_path: D:\Politecnico di Milano\Documentale DENG - PRIN-MIMO\Models\pyESM_docs\case_studies

database:
    database_name: database.db
    sets_excel_file_name: sets.xlsx
    input_data_dir_name: input_data
    input_data_hierarchy_map: 
        directories: 
            0: 
        files:
            files_name: scenarios
            sheets_name: variables

    # {directories: None, files: scenarios, sheets: variables}
    # hierarchy: {directories: scenarios, files: variables, sheets: None}
    # hierarchy: {directories: None, files: variables, sheets: scenarios}

problem:
    execution_mode: simulation