
model:
    name: test_case_1
    dir_path: D:\Politecnico di Milano\Documentale DENG - PRIN-MIMO\Models\pyESM_docs\case_studies
    description: dummy case study for testing the model
    use_existing_database: False # True if you want to rely on existing model directory and sql database
    generate_powerbi_report: False # this is not ready yet
    powerbi_report_name: data_browser.pbix

database:
    name: database.db
    sets_excel_file_name: sets.xlsx
    input_data_dir_name: input_data
    multiple_input_files: False
    input_file_name: input_data.xlsx
    foreign_keys: True

problem:
    execution_mode: simulation