
general:
    model_name: test_case_1
    model_description: dummy case study for testing the model
    model_data_dir_path: D:\Politecnico di Milano\Documentale DENG - PRIN-MIMO\Models\pyESM_docs\case_studies

database:
    database_name: database.db
    sets_excel_file_name: sets.xlsx
    input_data_dir_name: input_data
    multiple_input_files: False
    input_file_name: input_data.xlsx

problem:
    execution_mode: simulation